<?php
/**
 * 2016-06-02
 * «Login and Pay with Amazon Integration Guide» → «Step 3: Add a button widget»
 * https://payments.amazon.com/documentation/lpwa/201952050
 *
 * «Login with Amazon» → «Getting Started for Web» →  «3. Add the SDK for JavaScript»
 * http://login.amazon.com/website
 *
 * «Login with Amazon Developer Guide» → «Loading the JavaScript SDK»
 * https://images-na.ssl-images-amazon.com/images/G/01/lwa/dev/docs/website-developer-guide._TTH_.pdf
 * Page 17.
 */
use Dfe\LPA\Settings as S;
use Dfe\LPA\Settings\Login\Credentials as C;
/**
 * 2016-06-03
 * Сделал по аналогии с
 * https://github.com/amzn/amazon-payments-magento-plugin/blob/v1.4.2/app/code/community/Amazon/Payments/Block/Login/Script.php#L42
 *https://github.com/amzn/amazon-payments-magento-plugin/blob/v1.4.2/app/code/community/Amazon/Payments/Block/Script.php#L56
 */
/** @var string $widgetUrl */
$widgetUrl = df_cc_url(
	'https://static-na.payments-amazon.com/OffAmazonPayments/us'
	,S::s()->test() ? 'sandbox' : null
	,'js/Widgets.js?sellerId=' . S::s()->merchantId()
);
?>
<script type='text/javascript'>
	window.onAmazonLoginReady = function() {
		amazon.Login.setClientId('<?php echo df_ejs(C::s()->id()); ?>');
	};
</script>
<script async='async' type='text/javascript' src='<?php echo $widgetUrl; ?>'></script>
